### ISSUE TITLE
Link broken in readme.md

### ISSUE THREAD

**Issue by murillocg** [wedeploy-examples/java-maven-example#2]
This link doesn't exist anymore: https://ui-wedeploy.wedeploy.io/docs/deploy/deploying-java-maven.html

Sounds like maven was replaced by gradle: https://ui-wedeploy.wedeploy.io/docs/deploy/deploying-java.

I don't know if I should have created a issue for this. 
I just try to help you.

**Comment by zenorocha** [comment]
Thanks @murillocg!
